---
name: Publish Doc-Pages

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'docs/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    uses: jqassistant-tooling/jqassistant-github-actions/.github/workflows/publish-docs.yml@main
